In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import linear_model
import seaborn as sns
import matplotlib.pyplot as plt
from numpy.linalg import inv
from statsmodels.regression.linear_model import OLS

%matplotlib inline

In [2]:
daily = pd.read_csv("C:/Users/LENOVO/Desktop/ML/markov/Bike-Sharing-Dataset/day.csv")
daily.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0   
1        2  2011-01-02       1   0     1        0        0           0   
2        3  2011-01-03       1   0     1        0        1           1   
3        4  2011-01-04       1   0     1        0        2           1   
4        5  2011-01-05       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [3]:
daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
instant       731 non-null int64
dteday        731 non-null object
season        731 non-null int64
yr            731 non-null int64
mnth          731 non-null int64
holiday       731 non-null int64
weekday       731 non-null int64
workingday    731 non-null int64
weathersit    731 non-null int64
temp          731 non-null float64
atemp         731 non-null float64
hum           731 non-null float64
windspeed     731 non-null float64
casual        731 non-null int64
registered    731 non-null int64
cnt           731 non-null int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.5+ KB


In [4]:
for i in daily:
    if len(list(daily[i].unique())) < 10:
        print(i, list(daily[i].unique()))

season [1, 2, 3, 4]
yr [0, 1]
holiday [0, 1]
weekday [6, 0, 1, 2, 3, 4, 5]
workingday [0, 1]
weathersit [2, 1, 3]


In [5]:
df = daily[['atemp','hum','windspeed','cnt']]
df.head()

atemp       hum  windspeed   cnt
0  0.363625  0.805833   0.160446   985
1  0.353739  0.696087   0.248539   801
2  0.189405  0.437273   0.248309  1349
3  0.212122  0.590435   0.160296  1562
4  0.229270  0.436957   0.186900  1600

In [14]:
import random

theta_0 = random.random() 
theta_1 = random.random() 
theta_2 = random.random() 
theta_3 = random.random() 

alpha = 0.001



hist = -90
cost = 0
print('theta_0    + theta_1    +theta_2    + theta_3    ')

while(cost-hist>0.001):
    hist = cost
    cost = 0
    a = 0
    b = 0
    c = 0
    d = 0
    
    for i in range(len(df)):
        k = df.iloc[i]
        a = a +  theta_0 + theta_1*k[0] +theta_2*k[1] + theta_3*k[2] - k[3]
        b = b + (theta_0 + theta_1*k[0] +theta_2*k[1] + theta_3*k[2] - k[3])*k[0]
        c = c + (theta_0 + theta_1*k[0] +theta_2*k[1] + theta_3*k[2] - k[3])*k[1]
        d = d + (theta_0 + theta_1*k[0] +theta_2*k[1] + theta_3*k[2] - k[3])*k[2]
        
    theta_0 = theta_0 - alpha*a/len(df)
    theta_1 = theta_1 - alpha*b/len(df)
    theta_2 = theta_2 - alpha*c/len(df)
    theta_3 = theta_3 - alpha*d/len(df)
    
    #print(str(theta_0)+'    '+str(theta_1))
    for j in range(len(df)):
        k = df.iloc[i]
        cost  = cost + (theta_0 + theta_1*k[0] +theta_2*k[1] + theta_3*k[2] - k[3])**2
    cost = cost/(2*len(df))
   
    #print(cost)
    #if(cost>hist):
    #    print(str(theta_0)+'    '+str(theta_1))
    #    break
    
print(str(theta_0)+'    '+str(theta_1)+'    '+str(theta_2)+'    '+str(theta_3))

theta_0    + theta_1    +theta_2    + theta_3    
9.589088021475806    4.695675437818548    5.97399361084787    2.0486426746981268


In [9]:
X = df.iloc[:, df.columns != 'cnt']
Y = df.iloc[:, df.columns == 'cnt']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

In [10]:
reg = linear_model.LinearRegression() 

reg.fit(X_train, y_train) 
  

print('Coefficients: \n', reg.coef_)

Coefficients: 
 [[ 7223.02567388 -3550.02285209 -4340.85453652]]


In [19]:
clf = np.dot( np.linalg.inv(np.dot(X.T, X)) , np.dot(X.T, Y) )

In [20]:
print(clf)

[[9134.36185593]
 [ -13.91154047]
 [ 479.44751916]]


In [22]:
clf2 = np.dot( np.linalg.inv(np.dot(X_train.T, X_train)) , np.dot(X_train.T, y_train) )
print(clf2)

[[9155.63835462]
 [-133.61831868]
 [ 821.35708955]]


In [21]:
coeffs_cf = OLS( Y, X).fit().params
print(coeffs_cf)

atemp        9134.361856
hum           -13.911540
windspeed     479.447519
dtype: float64


In [23]:
coeffs_cf2 = OLS( y_train, X_train).fit().params
print(coeffs_cf2)

atemp        9155.638355
hum          -133.618319
windspeed     821.357090
dtype: float64
